use working vimcat from vimpager repository
source code taken from https://raw.githubusercontent.com/rkitover/vimpager/master/vimcat

diff --git a/vimcat b/vimcat
--- a/vimcat
+++ b/vimcat
@@ -1,155 +1,338 @@
-#!/bin/bash
-#!/usr/bin/env vim
-#! This is a bash script that executes itself as a vimscript to do its work
+#!/bin/sh
+version_tag=2.06
 
-: if 0
-  tmpfile=$(mktemp -t vimcat.XXXXXXXX)
-  exec 9<>"$tmpfile"
-  rm "$tmpfile"
+# FIND REAL PARENT DIRECTORY
+link=$0
 
-  [[ "${0:0:1}" == "/" ]] && script="$0" || script="$PWD/$0"
+while [ -h "$link" ]; do
+    ls0=`ls -l "$link"`
+    new_link=`expr "$ls0" : '.* -> \(.*\)$'`
+    if expr "$new_link" : '/.*' > /dev/null; then
+        link=$new_link
+    else
+        link=`dirname "$link"`/$new_link
+    fi
+done
 
-  /usr/bin/vim -e -X -R "$@" -c "source $script" -c "visual" -c "bufdo call AnsiHighlight()" -c qa >/dev/null 2>/dev/null
-  exec cat <&9
-: endif
+project_dir=`dirname "$link"`
+# END OF FIND REAL PARENT DIRECTORY
 
-" AnsiHighlight: Allows for marking up a file, using ANSI color escapes when
-" the syntax changes colors, for easy, faithful reproduction.
-" Author: Matthew Wozniski (mjw@drexel.edu)
-" Date: Fri, 01 Aug 2008 05:22:55 -0400
-" Version: 1.0 FIXME
-" History: FIXME see :help marklines-history
-" License: BSD. Completely open source, but I would like to be
-" credited if you use some of this code elsewhere.
+. "$project_dir/inc/prologue.sh"
 
-" Copyright (c) 2008, Matthew J. Wozniski {{{1
-" All rights reserved.
-"
-" Redistribution and use in source and binary forms, with or without
-" modification, are permitted provided that the following conditions are met:
-" * Redistributions of source code must retain the above copyright
-" notice, this list of conditions and the following disclaimer.
-" * Redistributions in binary form must reproduce the above copyright
-" notice, this list of conditions and the following disclaimer in the
-" documentation and/or other materials provided with the distribution.
-" * The names of the contributors may not be used to endorse or promote
-" products derived from this software without specific prior written
-" permission.
-"
-" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER ``AS IS'' AND ANY
-" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
-" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-" DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
-" DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
-" (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
-" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
-" ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
-" SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+[ -n "$ZSH_VERSION" ] && emulate -R sh 2>/dev/null # force zsh into full POSIX
 
-" Turn off vi-compatible mode, unless it's already off {{{1
-if &cp
-  set nocp
-endif
-let s:type = 'cterm'
-if &t_Co == 0
-  let s:type = 'term'
-endif
-" Converts info for a highlight group to a string of ANSI color escapes {{{1
-function! s:GroupToAnsi(groupnum)
-  if ! exists("s:ansicache")
-    let s:ansicache = {}
-  endif
+version="$(cd "$project_dir" && git describe 2>/dev/null) (git)" || version="$version_tag (checkout)"
+runtime=$project_dir
 
-  let groupnum = a:groupnum
+if command -v vim.basic >/dev/null; then
+    vim=vim.basic
+elif command -v vim >/dev/null; then
+    vim=vim
+elif command -v nvim >/dev/null; then
+    vim=nvim
+else
+    echo "$0: neither vim nor nvim found, vim or nvim is required for vimcat" >&2
+    exit 1
+fi
 
-  if groupnum == 0
-    let groupnum = hlID('Normal')
-  endif
+quit() {
+    (
+        kill "$vim_pid" >/dev/null 2>&1
+        do_sleep 100
+        kill -9 "$vim_pid" >/dev/null 2>&1
 
-  if has_key(s:ansicache, groupnum)
-    return s:ansicache[groupnum]
-  endif
+        kill "$pipeline_pid" >/dev/null 2>&1
+        do_sleep 100
+        kill -9 "$pipeline_pid" >/dev/null 2>&1
 
-  let fg = synIDattr(groupnum, 'fg', s:type)
-  let bg = synIDattr(groupnum, 'bg', s:type)
-  let rv = synIDattr(groupnum, 'reverse', s:type)
-  let bd = synIDattr(groupnum, 'bold', s:type)
+        kill "$tail_pid" >/dev/null 2>&1
+        do_sleep 100
+        if [ -f "${tmp_dir}/cat_pid" ]; then
+            cat_pid=$(cat "${tmp_dir}/cat_pid")
+            kill "$cat_pid" >/dev/null 2>&1
+        fi
+        kill -9 "$tail_pid" >/dev/null 2>&1
 
-  " FIXME other attributes?
-  if rv == "" || rv == -1
-    let rv = 0
-  endif
-  if bd == "" || bd == -1
-    let bd = 0
-  endif
-  if rv
-    let temp = bg
-    let bg = fg
-    let fg = temp
-  endif
-  if fg >= 8 && fg < 16
-    let fg -= 8
-    let bd = 1
-  endif
-  if fg == "" || fg == -1
-    unlet fg
-  endif
-  if !exists('fg') && !groupnum == hlID('Normal')
-    let fg = synIDattr(hlID('Normal'), 'fg', s:type)
-    if fg == "" || fg == -1
-      unlet fg
-    endif
-  endif
-  if bg == "" || bg == -1
-    unlet bg
-  endif
-  if !exists('bg') && !groupnum == hlID('Normal')
-    let bg = synIDattr(hlID('Normal'), 'bg', s:type)
-    if bg == "" || bg == -1
-      unlet bg
-    endif
-  endif
-  let retv = "\<Esc>[22;24;25;27;28"
-  if bd
-    let retv .= ";1"
-  endif
-  if exists('fg') && fg < 8
-    let retv .= ";3" . fg
-  elseif exists('fg')
-    let retv .= ";38;5;" . fg
-  endif
-  if exists('bg') && bg < 8
-    let retv .= ";4" . bg
-  elseif exists('bg')
-    let retv .= ";48;5;" . bg
-  endif
-  let retv .= "m"
-  let s:ansicache[groupnum] = retv
-  return retv
-endfunction
-function! AnsiHighlight()
-  let retv = []
-  for lnum in range(1, line('$'))
-    let last = hlID('Normal')
-    let output = s:GroupToAnsi(last) . "\<Esc>[K" " Clear to right
+        cd "${tmp_dir%/*}" 2>/dev/null # some systems cannot remove CWD
 
-        " Hopefully fix highlighting sync issues
-    exe "norm! " . lnum . "G$"
-    let line = getline(lnum)
-    for cnum in range(1, col('.'))
-      if synIDtrans(synID(lnum, cnum, 1)) != last
-        let last = synIDtrans(synID(lnum, cnum, 1))
-        let output .= s:GroupToAnsi(last)
-      endif
-      let output .= matchstr(line, '\%(\zs.\)\{'.cnum.'}')
-      "let line = substitute(line, '.', '', '')
-            "let line = matchstr(line, '^\@<!.*')
-    endfor
-    let retv += [output]
-  endfor
-  " Reset the colors to default after displaying the file
-  let retv[-1] .= "\<Esc>[0m"
+        rm -rf "$tmp_dir" 2>/dev/null # rm -rf "" shows error on OpenBSD
+    ) &
+    exit "$@"
+}
 
-  return writefile(retv, '/proc/self/fd/9')
-endfunction
+do_sleep() {
+    _ms=${1:-100}
+    "$vim" -NEsnR -i NONE -u NONE +"sleep $_ms m" +q >/dev/null 2>&1
+}
+
+usage() {
+    cat <<'EOF'
+Usage: [32mvimcat [1;34m[[1;35mOPTION[1;34m][0m... [1;34m[[1;35mFILE [1m| [1;35m-[1;34m][0m...
+Display [1;35mFILE[0m(s) in the terminal with (n)vim syntax highlighting using ANSI escape codes.
+
+With no [1;35mFILE[0m, or when [1;35mFILE[0m is [1;35m-[0m, read standard input.
+
+  [1m-h, --help, --usage[0m                This help screen.
+  [1m-v, --version[0m                      Show version information and exit.
+  [1m-n[0m                                 Print with line numbers.
+  [1m-s[0m                                 Squeeze multiple blank lines into one.
+  [1m-o [1;35mFILE[0m | [1;35m-[0m                        Output ANSI highlighted text to [1;35mFILE[0m or standard output.
+  [1m--cmd [1;35mCOMMAND[0m                      Run (n)vim [1;35mCOMMAND[0m before initialization.
+  [1m-c [1;35mCOMMAND[0m                         Run (n)vim [1;35mCOMMAND[0m after initialization.
+  [1m-u [1;35mFILE[0m                            Use [1;35mFILE[0m as the vimrc.
+  [1m-x [0m                                Give debugging output on stderr.
+
+Examples:
+  [32mvimcat [1;35mprogram.py[0m                  # output [1;35mprogram.py[0m with highlighting to terminal
+
+Project homepage: <[1;34mhttp://github.com/rkitover/vimpager[0m>
+and documentation: <[1;34mhttps://github.com/rkitover/vimpager/blob/master/markdown/vimcat.md[0m>
+or available locally via: [32mman [1;35mvimcat[0m
+EOF
+}
+
+write_chunks() {
+    cd "$chunks_dir"
+    rm -f -- *
+    split -b 4096 -
+    touch PIPELINE_DONE
+}
+
+start_pipeline() {
+    if [ -n "$pipeline" ]; then
+        pipeline="$pipeline | write_chunks"
+    else
+        pipeline=write_chunks
+    fi
+    cat -- "$pipeline_start" | (eval "$pipeline" <&3 & echo $! > "$tmp_dir/pipeline_pid") 3<&0
+    pipeline_pid=$(cat "$tmp_dir/pipeline_pid")
+}
+
+start_highlight_job() {
+    # INSERT VIMCAT_DEBUG PREPARATION HERE
+    set -- -NE -i NONE -n \
+        --cmd "set runtimepath^=$runtime" \
+        --cmd "call vimcat#Init({ 'rc': '$vimcatrc' })" \
+        --cmd visual \
+        ${extra_cmd:+--cmd "$extra_cmd"} \
+        ${extra_c:+-c "$extra_c"} \
+        -c "call vimcat#Run(\"$dest_file\", ${line_numbers:-0}, \"$chunks_dir\", \"$pipeline_start\")"
+
+    [ -n "$vimcatrc" ] && set -- "$@" -u "$vimcatrc"
+
+    if [ "${VIMCAT_DEBUG:-0}" -eq 0 ]; then
+        ("$vim" "$@" </dev/tty >/dev/null 2>&1; touch "$tmp_dir/vim_done") &
+        vim_pid=$!
+    else
+        "$vim" "$@" </dev/tty
+        touch "$tmp_dir/vim_done"
+    fi
+}
+
+squeeze_blank_lines() {
+    sed '/^[ 	]*$/{
+        N
+        /^[ 	]*\n[ 	]*$/D
+    }'
+}
+
+# if no args and stdin is on a terminal, pretend we're cat and wait on stdin.
+if [ $# -eq 0 -a -t 0 ]; then
+    exec cat
+fi
+
+# check for -h before main option parsing, this is much faster
+for arg in "$@"; do
+    case "$arg" in
+        "-h"|"--help"|"-help"|"--usage"|"-usage")
+            usage
+            quit 0
+            ;;
+        "-v"|"--version"|"-version")
+            echo "vimcat $version"
+            quit 0
+            ;;
+        "-x")
+            set -x
+            ;;
+    esac
+done
+
+tmp_dir=/tmp
+mkdir_options="-m 700"
+
+case "$(uname -s)" in
+    MINGW*|MSYS*)
+        if [ -n "$temp" ]; then
+            # MSYS2 is a little tricky, we're gonna stick to the user's private temp
+            # the -m mode switch to mkdir doesn't work
+            tmp_dir=$(cygpath --unix "$temp")
+            mkdir_options=
+        fi
+        ;;
+esac
+
+tmp_dir=$tmp_dir/vimcat_$$
+
+if ! mkdir $mkdir_options "$tmp_dir"; then
+    echo "Could not create temporary directory $tmp_dir" >&2
+    exit 1
+fi
+
+trap 'quit 1' PIPE HUP INT QUIT ILL TRAP KILL BUS TERM
+tmp_file_in=$tmp_dir/vimcat_in.txt
+out_fifo=$tmp_dir/vimcat_out.fifo
+
+mkfifo "$out_fifo"
+
+# check for arguments
+while [ $# -gt 0 ] ; do
+    case "$1" in
+        "-c")
+            shift
+            if [ -z "$extra_c" ]; then
+                extra_c=$1
+            else
+                extra_c="$extra_c | $1"
+            fi
+            shift
+            ;;
+        "--cmd")
+            shift
+            if [ -z "$extra_cmd" ]; then
+                extra_cmd=$1
+            else
+                extra_cmd="$extra_cmd | $1"
+            fi
+            shift
+            ;;
+        "-u")
+            shift
+            vimcatrc=$1
+            shift
+            ;;
+        "-o")
+            shift
+            output_file=$1
+            shift
+            ;;
+        "-s")
+            shift
+            squeeze_blank_lines=1
+            ;;
+        "-n")
+            shift
+            line_numbers=1
+            ;;
+        "-x")
+            # xtrace should already be set by the first option parsing
+            shift
+            ;;
+        "--")
+            shift
+            break
+            ;;
+        -)
+            break
+            ;;
+        -*)
+            echo "$0: bad option '$1', see --help for usage." >&2
+            quit 1
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
+
+# Just pass through if not on a tty, unless -o was given
+if [ -z "$output_file" ]; then
+    if [ ! -t 1 ]; then
+        exec cat "$@"
+    fi
+fi
+
+if [ -z "$vimcatrc" ]; then
+    if [ -f ~/.vimcatrc ]; then
+        vimcatrc=~/.vimcatrc
+    else
+        vimcatrc=
+    fi
+fi
+
+if [ $# -eq 0 ]; then
+    set -- -
+fi
+
+if [ -n "$output_file" -a $# -gt 1 ]; then
+    echo "$0: -o can only be used with one input file or stdin." >&2
+    quit 1
+fi
+
+chunks_dir=$tmp_dir/chunks
+mkdir "$chunks_dir"
+
+i=1
+for file in "$@"
+do
+    if [ $# -ge 2 ]; then
+        if [ $i -gt 1 ]; then
+            printf '\n'
+        fi
+        printf "==> %s <==\n\n" "$file"
+    fi
+
+    pipeline=
+    pipeline_start=$file
+
+    if [ "${squeeze_blank_lines:-0}" -eq 1 ]; then
+        pipeline=squeeze_blank_lines
+    fi
+
+    exit_code=0
+
+    # Check that the file is readable
+    if [ "$file" != - ]; then
+        if [ ! -r "$file" ]; then
+            echo "$0: Cannot read file: $file" >&2
+            exit_code=1
+        fi
+
+        [ ! -s "$file" ] && continue
+    fi
+
+    if [ -z "$output_file" -o "$output_file" = "-" ]; then
+        dest_file=$out_fifo
+
+        (
+            while :; do
+                cat "$out_fifo" & cat_pid=$!
+                echo ${cat_pid} > "${tmp_dir}/cat_pid"
+                wait ${cat_pid}
+            done
+        ) &
+        tail_pid=$!
+    else
+        dest_file=$output_file
+        printf '' > "$dest_file"
+    fi
+
+    start_highlight_job
+    start_pipeline
+    while [ ! -f "$tmp_dir/vim_done" ]; do
+        do_sleep 50
+    done
+
+    if [ -n "$tail_pid" ]; then
+        # if it's not a fifo where this doesn't work, tail needs some time to catch up
+        [ ! -p "$out_fifo" ] && do_sleep 1100
+
+        kill $tail_pid >/dev/null 2>&1
+    fi
+
+    i=$((i + 1))
+done
+
+quit $exit_code
+
+# vim: sw=4 et ft=sh
